// frontend-angular/src/app/modules/administraciones/articles/modals/article.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';
import { Global } from 'src/app/app-config/default';
import { Article } from '../services/article';
import { ArticleService } from '../services/article.service';
import Swal from 'sweetalert';

@Component({
  selector: 'app-article',
  templateUrl: './article.component.html',
  styleUrls: ['./article.component.css'],
  providers: [
    ArticleService
  ]
})
export class ArticleComponent implements OnInit {
  article!: Article;
  url!: string;

  constructor(
    private _activeRoute: ActivatedRoute,
    private _router: Router,
    private _articleService: ArticleService
  ) {
    this.url = Global.url;
  }

  ngOnInit(): void {
    this._activeRoute.params.subscribe((params: Params) => {
      this._articleService.getArticleById(params['id']).subscribe(response => {
        if (!response.article) {
          this._router.navigate(['/inicio']);  
        }
        this.article = response.article;
      }, error => {
        this._router.navigate(['/inicio']);
      });
    });
  }

  deleteArticle(id: string): void {
    Swal({
      title: "¿Estas seguro?",
      text: "Una vez eliminado, no podrá recuperar el registro!",
      icon: "warning",
      buttons: [true, true],
      dangerMode: true
    })
    .then((willDelete) => {
      if (willDelete) {
        this._articleService.deleteArticle(id).subscribe(response => {
          Swal("Su articulo ha sido eliminado!", {
            icon: response.status
          });
          this._router.navigate(['/blog']);
        }, error => {
          Swal("Error al eliminar!", {            
            icon: error.status
          });
          this._router.navigate(['/blog']);  
        });        
      }
    });    
  }
}

<div class="center">
  <section id="content">
    <article class="article-item article-detail" id="article-detail" *ngIf="article">
      <div class="image-wrap">
        <img
          src="{{ url + '/article/imagen/' + article.image }}"
          alt="{{ article.title }}"
          onerror="this.onerror=null;this.src='assets/images/default.jpg'" />
      </div>
      <h1 class="subheader">{{ article.title }}</h1>
      <span class="date">
        {{ article.date | amLocale: 'es' | amTimeAgo }}
      </span>
      <p>
        {{ article.content }}
      </p>
      <div class="buttons">
        <a [routerLink]="['/blog/editar', article._id]" class="btn btn-warning">Editar</a>
        <a (click)="deleteArticle(article._id)" class="btn btn-danger">Borrar</a>
      </div>
      <div class="clearfix"></div>
    </article>
  </section>
  <app-sidebar></app-sidebar>
</div>

// frontend-vue/src/components/modules/administraciones/articles/modals/ArticleComponent.vue
<template>
  <div class="general">
    <div class="center">
      <section id="content">
        <article class="article-item article-detail" id="article-detail">
          <div class="image-wrap">
            <img v-if="article.image" :src="url + '/article/imagen/' + article.image" :alt="article.title" />
            <img v-if="!article.image" src="./../../../../../assets/images/default.jpg" alt="Image Default" />
          </div>
          <h1 class="subheader">{{ article.title }}</h1>
          <span class="date">
            {{ dateTime(article.date) }}
          </span>
          <p>
            {{ article.content }}
          </p>
          <div class="buttons">
            <RouterLink :to="{ path: 'blog/editar', name: 'ArticleUpdate', params: { id: article._id } }"
              class="btn btn-warning">Editar</RouterLink>
            <button @click="deleteArticle()" class="btn btn-danger">Borrar</button>
          </div>
          <div class="clearfix"></div>
        </article>
      </section>
      <SidebarComponent></SidebarComponent>
      <div class="clearfix"></div>
    </div>
  </div>
</template>
<script>
import Moment from 'moment';
import Axios from 'axios';
import Swal from 'sweetalert';
import Global from './../../../../app-config/Default';

import SidebarComponent from './../../../../layout/sidebar/SidebarComponent.vue';

export default {
  name: 'ArticleComponent',
  components: {
    SidebarComponent
  },
  mounted() {
    this.idArticle = this.$route.params.id;
    this.getArticleById();
  },
  computed: {
    dateTime(value) {
      return Moment(value, "YYYYMMDD").fromNow();
    },
  },
  data() {
    return {
      url: Global.url,
      idArticle: null,
      article: {}
    };
  },
  methods: {
    getArticleById() {
      let urlArticle = this.url + '/article/' + this.idArticle;
      Axios.get(urlArticle).then(response => {
        this.article = response.data.article;
      }).catch(function (error) {
        this.article = {};
      });
    },
    deleteArticle() {
      Swal({
        title: "¿Estas seguro?",
        text: "Una vez eliminado, no podrá recuperar el registro!",
        icon: "warning",
        buttons: [true, true],
        dangerMode: true
      }).then((willDelete) => {
        if (willDelete) {
          let urlArticle = this.url + '/article/' + this.idArticle;
          Axios.delete(urlArticle).then(response => {
            this.article = response.data.article;
            Swal("Su articulo ha sido eliminado!", {
              icon: response.data.status
            });
            this.$router.push('/blog');
          }).catch(function (error) {
            this.article = {};
            Swal("Error al eliminar!", {
              icon: error.data.status
            });
          });
        }
      });
    }
  }
}
</script>
