// frontend-vue/src/components/layout/slider/SliderComponent.vue
<template>
  <div id="slider" :class="{ 'slider-big': !size || size == 'big', 'slider-small': size == 'small' }">
    <h1>{{ defaultText }}</h1>
    <RouterLink to="blog" class="btn-white" v-if="isViewButton">Ir al blog</RouterLink>
  </div>
</template>

<script>
import { RouterLink } from 'vue-router';

export default {
  name: "SliderComponent",
  props: {
    isViewButton: {
      type: Boolean
    },
    defaultText: {
      type: String
    },
    size: {
      type: String
    }
  },
  components: { RouterLink }
}
</script>

// frontend-react/src/app/layout/slider/Slider.js
import React, { Component } from 'react';
import { Link } from 'react-router-dom';

class Slider extends Component {
  render() {
    return (
      <div id="slider" className={this.props.size}>
        <h1>{this.props.nombre}</h1>
        {this.props.button && <Link to="/blog" className="btn-white">{this.props.button}</Link>}        
      </div>
    );
  }
}

export default Slider;
