// frontend-angular/src/app/layout/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent implements OnInit {
  search!: string;

  constructor(
    private _router: Router
  ) { }

  ngOnInit(): void {

  }

  onSearch(): void {
    this._router.navigate(['/buscar', this.search]);
  }
}

<aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
        <h3>{{'TextosAplicacion.TituloSidebar' | translate}}</h3>
        <a [routerLink]="['/blog/crear']" class="btn btn-success">{{'TextosAplicacion.TextoCrearArticulo' | translate}}</a>
    </div>
    <div id="search" class="sidebar-item">
        <h3>{{'Generic.Buttons.Buscador' | translate}}</h3>
        <p>{{'TextosAplicacion.TextoBusqueda' | translate}}</p>
        <form #searchForm="ngForm" (ngSubmit)="onSearch()">
            <input type="text" name="search" aria-label="search" #search="ngModel" [(ngModel)]="search" />
            <input type="submit" name="submit" value="Buscar" class="btn" />
        </form>
    </div>
</aside>
<div class="clearfix"></div>

// frontend-vue/src/components/layout/sidebar/SidebarComponent.vue
<template>
  <aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
      <h3>Puedes hacer esto</h3>
      <a href="#" class="btn btn-success">Crear artículo</a>
    </div>

    <div id="search" class="sidebar-item">
      <h3>Buscador</h3>
      <p>Encuentra el artículo que buscas</p>
      <form>
        <input type="text" name="search" aria-label="search" />
        <input type="submit" name="submit" value="Buscar" class="btn" />
      </form>
    </div>
  </aside>
</template>

<script>
export default {
  name: 'SidebarComponent'
}
</script>
