// frontend-react/src/app/modules/administraciones/articles/modals/ArticleCreate.js
import React, { Component } from 'react';
import { Navigate } from 'react-router-dom';
import Axios from 'axios';

import Global from './../../../../app-config/Default';
import Sidebar from './../../../../layout/sidebar/Sidebar';

class ArticleCreate extends Component {
  state = {
    article: {},
    status: null,
    selectedFile: null
  };
  url = Global.url;

  titleRef = React.createRef();
  contentsRef = React.createRef();

  changeState = () => {
    this.setState({
      article: {
        title: this.titleRef.current.value,
        content: this.contentsRef.current.value
      }
    });
  };

  fileChange = (event) => {
    this.setState({
      selectedFile: event.target.file[0]
    })
  };

  formSubmit = (e) => {
    e.preventDefault();
    let urlArticle = this.url + '/article';
    Axios.post(urlArticle, this.state.article).then(response => {
      this.setState({
        article: response.data.article,
        status: 'waiting'
      });
      let idArticle = response.article._id;
      let formData = new FormData();
      if (this.state.selectedFile !== null) {
        formData.append('file0', this.state.selectedFile, this.state.selectedFile.name);
        Axios.post('/article/upload/' + idArticle, formData).then(responseFile => {
          this.setState({
            article: responseFile.data.article,
            status: responseFile.data.status
          });
        });
      }      
    }).catch(function (error) {
      this.setState({
        article: {},
        status: error.status
      });
    });
  };

  render() {
    if (this.state.status === 'success') {
      return <Navigate to={'/blog'} />
    }
    return (
      <React.Fragment>
        <div className="center">
          <section id="content">
            <h1 className="subheader">Crear artículo</h1>
            <form className="mid-form" onSubmit={this.formSubmit}>
              <div className="form-group">
                <label htmlFor="title">Titulo</label>
                <input type="text" name="title" id="title" ref={this.titleRef} onChange={this.changeState} required />
                <small>
                  El titulo es requerido
                </small>
              </div>

              <div className="form-group">
                <label htmlFor="contents">Contenido</label>
                <textarea name="contents" id="contents" ref={this.contentsRef} onChange={this.changeState} required></textarea>
                <small>
                  El contenido es requerida
                </small>
              </div>

              <div className="form-group">
                <input type="file" name="file0" id="imagen" accept=".jpg, .jpeg, .png" aria-label="file0" onChange={this.fileChange} />                
              </div>

              <div className="clearfix"></div>
              <input type="submit" value="Crear" className="btn btn-success" />
            </form>
          </section>
          <Sidebar />
        </div>
      </React.Fragment>
    );
  }
}

export default ArticleCreate;

// frontend-angular/src/app/modules/administraciones/articles/modals/article-create.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Article } from '../services/article';
import { ArticleService } from '../services/article.service';

@Component({
  selector: 'app-article-create',
  templateUrl: './article-create.component.html',
  styleUrls: ['./article-create.component.css'],
  providers: [
    ArticleService
  ]
})
export class ArticleCreateComponent implements OnInit {
  article!: Article;
  status!: string;

  constructor(
    private _router: Router,
    private _articleService: ArticleService
  ) { }

  ngOnInit(): void {

  }

  onSubmit(): void {
    this._articleService.saveArticle(this.article).subscribe(response => {
      this.status = response.status;
      this.article = response.article;
      this._router.navigate(['/blog']);  
    }, error => {
      this.status = error.status;
    });
  }
}

<div class="center">
  <section id="content">
    <h1 class="subheader">Crear artículo</h1>
    <form class="mid-form" #articleForm="ngForm" (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="title">Titulo</label>
        <input type="text" name="title" id="title" #title="ngModel" [(ngModel)]="article.title" required>
        <small *ngIf="!title.valid && title.touched">
          El titulo es requerido
        </small>
      </div>

      <div class="form-group">
        <label for="content">Contenido</label>
        <textarea name="content" id="content" #content="ngModel" [(ngModel)]="article.content" required></textarea>
        <small *ngIf="!content.valid && content.touched">
          El contenido es requerida
        </small>
      </div>

      <div class="form-group">
        <label for="imgage">Imagen</label>
        <input type="file" name="file0" id="imgage">
      </div>
      
      <div class="clearfix"></div>

      <input type="submit" value="Crear" class="btn btn-success" [disabled]="articleForm.invalid" />
    </form>
  </section>
  <app-sidebar></app-sidebar>
</div>
