// frontend-react/src/app/modules/administraciones/articles/modals/ArticleUpdate.js
import React, { Component } from 'react';
import { Navigate } from 'react-router-dom';
import Axios from 'axios';
import SimpleReactValidator from 'simple-react-validator';
import Swal from 'sweetalert';

import DefaultImage from './../../../../../assets/images/default.jpg';
import withRouter from './../../../../../withRouter';
import Global from './../../../../app-config/Default';
import Sidebar from './../../../../layout/sidebar/Sidebar';

class ArticleUpdate extends Component {
  state = {
    article: {},
    status: null,
    selectedFile: null
  };
  url = Global.url;
  idArticle = null;

  titleRef = React.createRef();
  contentsRef = React.createRef();

  constructor(props) {
    super(props);
    this.validator = new SimpleReactValidator();
  }

  componentDidMount() {
    this.idArticle = this.props.params.id;
    this.getArticleById();
  }

  changeState = () => {
    this.setState({
      article: {
        title: this.titleRef.current.value,
        content: this.contentsRef.current.value,
        image: this.state.article.image
      }
    });
  };

  fileChange = (event) => {
    this.setState({
      selectedFile: event.target.files[0]
    })
  };

  getArticleById = () => {
    let urlArticle = this.url + '/article/' + this.idArticle;
    Axios.get(urlArticle).then(response => {
      console.log(response);
      this.setState({
        article: response.data.article,
        status: response.data.status
      });
    }).catch(function (error) {
      this.setState({
        article: {},
        status: error.data.status
      });
    });
  }

  formSubmit = (e) => {
    e.preventDefault();
    if (this.validator.allValid()) {
      let urlArticle = this.url + '/article/' + this.idArticle;
      Axios.put(urlArticle, this.state.article).then(response => {
        this.setState({
          article: response.data.article,
          status: 'waiting'
        });
        if (this.state.selectedFile !== null) {
          let idArticle = response.data.article._id;
          let formData = new FormData();
          let urlImageArticle = this.url + '/article/upload/' + idArticle;

          formData.append('file0', this.state.selectedFile, this.state.selectedFile.name);

          Axios.post(urlImageArticle, formData).then(responseFile => {
            this.setState({
              article: responseFile.data.article,
              status: 'update'
            });
          });
        } else {
          this.setState({
            status: 'update'
          });
        }
        Swal({
          title: "Articulo actualizado!",
          text: "El articulo se ha actualizado correctamente!",
          icon: response.data.status
        });
      }).catch(function (error) {
        this.setState({
          status: error.data.status
        });
        Swal({
          title: "Error al actualizar!",
          text: error.message,
          icon: error.status
        });
      });
    } else {
      this.setState({
        status: 'faild'
      });
      this.validator.showMessages();
      this.forceUpdate();
    }
  };

  render() {
    if (this.state.status === 'update') {
      return <Navigate to={'/blog'} />
    }
    return (
      <React.Fragment>
        <div className="center">
          <section id="content">
            <h1 className="subheader">Actualizar artículo</h1>
            <form className="mid-form" onSubmit={this.formSubmit}>
              <div className="form-group">
                <label htmlFor="title">Titulo</label>
                <input type="text" name="title" id="title" defaultValue={this.state.article.title} ref={this.titleRef} onChange={this.changeState} required />
                {this.validator.message('title', this.state.article.title, 'required|min:5|max:50')}
              </div>

              <div className="form-group">
                <label htmlFor="contents">Contenido</label>
                <textarea name="contents" id="contents" defaultValue={this.state.article.content} ref={this.contentsRef} onChange={this.changeState} required></textarea>
                {this.validator.message('contents', this.state.article.content, 'required|min:10|max:1000')}
              </div>

              <div className="form-group">
                <div className="image-thumb">
                  {                    
                    this.state.article.image !== null ? (
                      <img src={this.url + '/article/imagen/' + this.state.article.image} alt={this.state.article.title} />
                    ) : (
                      <img src={DefaultImage} alt={this.state.article.title} />
                    )
                  }
                </div>
                <input type="file" name="file0" id="imagen" accept=".jpg, .jpeg, .png" aria-label="file0" onChange={this.fileChange} />
              </div>

              <div className="clearfix"></div>
              <input type="submit" value="Crear" className="btn btn-success" />
            </form>
          </section>
          <Sidebar />
        </div>
      </React.Fragment>
    );
  }
}

export default withRouter(ArticleUpdate);

// frontend-angular/src/app/modules/administraciones/articles/modals/article-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router, Params } from '@angular/router';
import { Global } from 'src/app/app-config/default';
import { NamesIdentity } from 'src/app/app-core/core/enum/name.identity.enum';
import { Article } from '../services/article';
import { ArticleService } from '../services/article.service';
import Swal from 'sweetalert';

@Component({
  selector: 'app-article-update',
  templateUrl: './article-update.component.html',
  styleUrls: ['./article-update.component.css'],
  providers: [
    ArticleService
  ]
})
export class ArticleUpdateComponent implements OnInit {
  article: Article = new Article('', '', '');
  url!: string;
  idArticle!: string;
  afuConfigImage: any;

  constructor(
    private _activeRoute: ActivatedRoute,
    private _router: Router,
    private _articleService: ArticleService
  ) { 
    this.url = Global.url;
  }

  ngOnInit(): void {
    this._activeRoute.params.subscribe((params: Params) => {      
      this.idArticle = params['id'];
    });
    this.cargarConfiguraciones();
    this.getArticle();    
  }

  /**
   * Este método carga las configuraciones para exportar
   * @returs {*} 
   * @membersof ArticleCreateComponent
   * @author Deivis Andres Herrera Julio
   */
  cargarConfiguraciones() {
    this.afuConfigImage = {
      multiple: false,
      formatsAllowed: '.jpg,.png,.gif,.jpeg',
      maxSize: '50',
      uploadAPI: {
        url: `${this.url}/article/upload`,
        method: 'POST'
      },
      theme: 'attachPin',
      hideProgressBar: true,
      hideResetBtn: true,
      hideSelectBtn: false,
      replaceTexts: {
        selectFileBtn: NamesIdentity.CargaArchivoImage,
        resetBtn: NamesIdentity.Reiniciar,
        uploadBtn: NamesIdentity.Cargar,
        attachPinBtn: NamesIdentity.CargaArchivoImage,
        afterUploadMsg_success: NamesIdentity.CargaMensajeExitoso,
        afterUploadMsg_error: NamesIdentity.CargaMensajeError,
        sizeLimit: NamesIdentity.CargaLimitePeso
      } 
    };
  }

  /**
   * Este método se utiliza para cargar los documentos para exportar
   * @returs {*} 
   * @membersof ArticleCreateComponent
   * @param data Object to return a value type any
   * @author Deivis Andres Herrera Julio
   */
  imgageUpload(data: any) {
    let response = data.body;
    this.article.image = response.image;
  }

  getArticle(): void {
    this._articleService.getArticleById(this.idArticle).subscribe(response => {
      this.article = response.article;
    });
  }

  onSubmit(): void {
    this._articleService.updateArticle(this.idArticle, this.article).subscribe(response => {
      this.article = response.article;
      Swal({
        title: "Articulo actualizado!",
        text: "El articulo se ha actualizado correctamente!",
        icon: response.status
      });
      this._router.navigate(['/blog/articulo', this.idArticle]);  
    }, error => {
      Swal({
        title: "Error al actualizar!",
        text: error.message,
        icon: error.status
      });
    });
  }
}

<div class="center">
  <section id="content">
    <h1 class="subheader">Editar artículo</h1>
    <form class="mid-form" #articleForm="ngForm" (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="title">Titulo</label>
        <input type="text" name="title" id="title" #title="ngModel" [(ngModel)]="article.title" required>
        <small *ngIf="!title.valid && title.touched">
          El titulo es requerido
        </small>
      </div>

      <div class="form-group">
        <label for="content">Contenido</label>
        <textarea name="content" id="content" #content="ngModel" [(ngModel)]="article.content" required></textarea>
        <small *ngIf="!content.valid && content.touched">
          El contenido es requerida
        </small>
      </div>

      <div class="form-group">
        <div class="image-thumb">
          <img
            src="{{ url + '/article/imagen/' + article.image }}"
            alt="{{ article.title }}"
            onerror="this.onerror=null;this.src='assets/images/default.jpg'" />
        </div>
        <angular-file-uploader [config]="afuConfigImage" (ApiResponse)="imgageUpload($event)">
        </angular-file-uploader>
      </div>

      <div class="clearfix"></div>

      <input type="submit" value="Crear" class="btn btn-success" [disabled]="articleForm.invalid" />
    </form>
  </section>
  <app-sidebar></app-sidebar>
</div>
