// frontend-react/src/app/modules/administraciones/peliculas/modals/Pelicula.js
import React, { Component } from 'react';

class Pelicula extends Component {
  seleccionarPelicula = () => {
    this.props.seleccionarPelicula(this.props.pelicula);
  };

  render() {
    const { title, year, image } = this.props.pelicula;
    return (
      <div id="articles">
        <article className="article-item" id={"article-template-" + this.props.index}>
          <div className="image-wrap">
            <img src={image} alt={title} />
          </div>
          <h2>{title}</h2>
          <span className="date">
            {year}
          </span>
          <a href="#">Leer más</a>
          <button onClick={this.seleccionarPelicula}>Seleccionar como favorita</button>
          <div className="clearfix"></div>
        </article>
      </div>
    );
  }
}

export default Pelicula

// frontend-angular/src/app/modules/administraciones/pelicula/pelicula.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { Pelicula } from './services/pelicula';

@Component({
  selector: 'app-pelicula',
  templateUrl: './pelicula.component.html',
  styleUrls: ['./pelicula.component.css']
})
export class PeliculaComponent implements OnInit {
  @Input() pelicula!: Pelicula;
  @Output() eventFavorito = new EventEmitter();

  constructor() { }

  ngOnInit(): void {

  }

  seleccionarPelicula(pelicula: Pelicula): void {
    this.eventFavorito.emit({
      pelicula: pelicula
    });
  }
}

<article class="article-item">
  <div class="image-wrap">
    <img src="{{pelicula.image}}" alt="{{pelicula.title}}" />
  </div>
  <h2>{{pelicula.title}}</h2>
  <span class="date">
    Hace 5 minutos
  </span>
  <span class="year" [ngClass]="{ 'year-green': pelicula.year > 2020, 'year-red': pelicula.year <= 2020 }">
    {{pelicula.year}}
  </span>
  <a href="#">Leer más</a>
  <button (click)="seleccionarPelicula(pelicula)">Seleccionar como favorita</button>
  <div class="clearfix"></div>
</article>
