// frontend-angular/src/app/modules/administraciones/blog/blog.component.ts
import { Component, OnInit } from '@angular/core';
import { Article } from './services/article';
import { ArticleService } from './services/article.service';
import { Global } from '../../../app-config/default';

@Component({
  selector: 'app-blog',
  templateUrl: './blog.component.html',
  styleUrls: ['./blog.component.css'],
  providers: [
    ArticleService
  ]
})
export class BlogComponent implements OnInit {
  articles: Article[] = [];
  url!: string;
  
  constructor(
    private _articleService: ArticleService
  ) { 
    this.url = Global.url;
  }

  ngOnInit(): void {
    this._articleService.getArticles().subscribe(response => {
      this.articles = response.articles;
    }, error => {
      console.log(error);
    });
  }

}

<app-slider [nombre]="'Blog'" [size]="'small'"></app-slider>
<div class="center">
  <section id="content">
    <app-articles [articles]="articles"></app-articles>
  </section>
  <app-sidebar></app-sidebar>
</div>

// frontend-vue/src/components/modules/administraciones/blog/BlogComponent.vue
<template>
  <div class="general">
    <SliderComponent :isViewButton="false" :defaultText="'Blog'" :size="'small'"></SliderComponent>
    <div class="center">
      <section id="content">
        <h2 class="subheader">Blog</h2>
        <ArticlesComponent :articles="articles"></ArticlesComponent>
      </section>
      <SidebarComponent></SidebarComponent>
      <div class="clearfix"></div>
    </div>
  </div>
</template>
<script>
import Axios from 'axios';
import Global from './../../../app-config/Default';

import SliderComponent from './../../../layout/slider/SliderComponent.vue';
import SidebarComponent from './../../../layout/sidebar/SidebarComponent.vue';
import ArticlesComponent from './../articles/ArticlesComponent.vue'

export default {
  name: 'BlogComponent',
  components: {
    SliderComponent,
    SidebarComponent,
    ArticlesComponent
  },
  mounted() {
    this.getArticles();
  },
  data() {
    return {
      url: Global.url,
      status: null,
      articles: []
    };
  },
  methods: {
    getArticles() {
      let lastArticles = this.props.lastArticles;
      let searchedArticle = this.props.searchedArticle;
      let urlArticles = this.url + '/articles';

      if (lastArticles && !searchedArticle) {
        urlArticles += '/' + lastArticles;
      } else if (!lastArticles && searchedArticle) {
        urlArticles = this.url + '/article/search/' + searchedArticle;
      }

      Axios.get(urlArticles).then(response => {
        this.articles = response.data.articles;
      }).catch(function (error) {
        console.log(error);
        this.articles = [];
      });
    }
  }
}
</script>
