// frontend-vue/src/components/modules/administraciones/articles/modals/ArticleComponent.vue
<template>
  <div class="general">
    <div class="center">
      <section id="content">
        <article class="article-item article-detail" id="article-detail">
          <div class="image-wrap">
            <img v-if="article.image" :src="url + '/article/imagen/' + article.image" :alt="article.title" />
            <img v-if="!article.image" src="./../../../../../assets/images/default.jpg" alt="Image Default" />
          </div>
          <h1 class="subheader">{{ article.title }}</h1>
          <span class="date">
            {{ dateTime(article.date) }}
          </span>
          <p>
            {{ article.content }}
          </p>
          <div class="buttons">
            <a @click="redirectUpdateArticle()" class="btn btn-warning">Editar</a>
            <a @click="deleteArticle()" class="btn btn-danger">Borrar</a>
          </div>
          <div class="clearfix"></div>
        </article>
      </section>
      <SidebarComponent></SidebarComponent>
      <div class="clearfix"></div>
    </div>
  </div>
</template>
<script>
import Moment from 'moment';
import Axios from 'axios';
import Swal from 'sweetalert';
import Global from './../../../../app-config/Default';

import SidebarComponent from './../../../../layout/sidebar/SidebarComponent.vue';

export default {
  name: 'ArticleComponent',
  components: {
    SidebarComponent
  },
  mounted() {
    this.idArticle = this.$route.params.id;
    this.getArticleById();
  },
  data() {
    return {
      url: Global.url,
      idArticle: null,
      article: {}
    };
  },
  methods: {
    getArticleById() {
      let urlArticle = this.url + '/article/' + this.idArticle;
      Axios.get(urlArticle).then(response => {
        this.article = response.data.article;
      }).catch(function() {
        this.article = {};
      });
    },
    deleteArticle() {
      Swal({
        title: "¿Estas seguro?",
        text: "Una vez eliminado, no podrá recuperar el registro!",
        icon: "warning",
        buttons: [true, true],
        dangerMode: true
      }).then((willDelete) => {
        if (willDelete) {
          let urlArticle = this.url + '/article/' + this.idArticle;
          Axios.delete(urlArticle).then(response => {
            this.article = response.data.article;
            Swal("Su articulo ha sido eliminado!", {
              icon: response.data.status
            });
            this.$router.push('/blog');
          }).catch(function (error) {
            this.article = {};
            Swal("Error al eliminar!", {
              icon: error.data.status
            });
          });
        }
      });
    },
    dateTime(value) {      
      return Moment(value, "YYYYMMDD").fromNow();
    },
    redirectUpdateArticle() {
      this.$router.push('/blog/editar/' + this.idArticle);
    }
  }
}
</script>

// frontend-react/src/app/modules/administraciones/articles/modals/Article.js
import React, { Component } from 'react';
import { Link, Navigate } from 'react-router-dom';
import Axios from 'axios';
import Moment from 'react-moment';
import Swal from 'sweetalert';

import withRouter from './../../../../../withRouter';
import DefaultImage from './../../../../../assets/images/default.jpg';
import Global from './../../../../app-config/Default';
import Sidebar from './../../../../layout/sidebar/Sidebar';
import Slider from './../../../../layout/slider/Slider';

class Article extends Component {
  state = {
    article: null,
    status: null
  };  
  url = Global.url;

  componentDidMount() {
    this.getArticleById();
  }

  getArticleById = () => {
    let idArticle = this.props.params.id;
    let urlArticle = this.url + '/article/' + idArticle;

    Axios.get(urlArticle).then(response => {
      this.setState({
        article: response.data.article,
        status: response.data.status
      });
    }).catch(function (error) {
      this.setState({
        article: {},
        status: error.data.status
      });
    });
  }

  deleteArticle = (idArticle) => {
    Swal({
      title: "¿Estas seguro?",
      text: "Una vez eliminado, no podrá recuperar el registro!",
      icon: "warning",
      buttons: [true, true],
      dangerMode: true
    })
    .then((willDelete) => {
      if (willDelete) {
        let urlArticle = this.url + '/article/' + idArticle;
        Axios.delete(urlArticle).then(response => {
          this.setState({
            article: response.data.article,
            status: 'deleted'
          });
          Swal("Su articulo ha sido eliminado!", {
            icon: response.data.status
          });
        }).catch(function (error) {
          this.setState({
            article: {},
            status: error.data.status
          });
          Swal("Error al eliminar!", {            
            icon: error.data.status
          }); 
        });        
      }
    });
  }

  render() {
    let article = this.state.article;
    if (this.state.status === 'deleted') {
      return <Navigate to={'/blog'} />
    }
    return (
      <React.Fragment>
        <Slider nombre="Articulo" size="slider-small" />
        <div className="center">
          <section id="content">
            {article &&
              <article className="article-item article-detail" id="article-detail">
                <div className="image-wrap">
                  {
                    article.image !== null ? (
                      <img src={this.url + '/article/imagen/' + article.image} alt={article.title} />
                    ) : (
                      <img src={DefaultImage} alt={article.title} />
                    )
                  }
                </div>
                <h1 className="subheader">{article.title}</h1>
                <span className="date">
                  <Moment locale='es' fromNow>{article.date}</Moment>
                </span>
                <p>
                  {article.content}
                </p>
                <div className="buttons">
                  <Link to={'/blog/editar/' + article._id} className="btn btn-warning">Editar</Link>
                  <Link onClick={ () => { this.deleteArticle(article._id) } } className="btn btn-danger">Borrar</Link>
                </div>
                <div className="clearfix"></div>
              </article>
            }
          </section>
          <Sidebar />
        </div>
      </React.Fragment>
    );
  }
}

export default withRouter(Article);
