// frontend-vue/src/components/modules/administraciones/articles/modals/ArticleCreate.vue
<template src="./../template/ArticleCreate.html"></template>
<script>
import Axios from 'axios';
import Swal from 'sweetalert';

import Global from './../../../../app-config/Default';
import useVuelidate from '@vuelidate/core'
import { required } from '@vuelidate/validators'

import ArticleModel from './../services/ArticleModel';

import SidebarComponent from './../../../../layout/sidebar/SidebarComponent.vue';

export default {
  name: 'ArticleCreate',
  components: {
    SidebarComponent
  },
  setup() {
    return { v$: useVuelidate() }
  },
  validations() {
    return {
      article: {
        title: { required },
        content: { required }
      }
    }
  },
  data() {
    return {
      url: Global.url,
      article: new ArticleModel('', '', null, null),
      file: null
    };
  },
  methods: {
    formSubmit() {
      this.v$.$validate();
      if (!this.v$.$error) {
        let urlArticle = this.url + '/article';
        Axios.post(urlArticle, this.article).then(response => {
          this.article = response.data.articleStored;
          if (this.file !== null) {
            let idArticle = response.data.articleStored._id;
            let formData = new FormData();
            let urlImageArticle = this.url + '/article/upload/' + idArticle;
            formData.append('file0', this.file, this.file.name);
            Axios.post(urlImageArticle, formData).then(responseFile => {
              this.article = responseFile.data.article;
            });
          }
          Swal({
            title: "Articulo creado!",
            text: "El articulo se ha creado correctamente!",
            icon: response.data.status
          });
          this.$router.push('/blog');
        }).catch(function (error) {
          Swal({
            title: "Error al crear!",
            text: error.data.message,
            icon: error.data.status
          });
        });
      } else {
        Swal({
          text: 'Verifique que los campos requeridos esten diligenciados correctamente.',
          icon: 'warning'
        });
        return false;
      }
    },
    fileChange() {
      this.file = this.$refs.file.files[0];
    }
  }
}
</script>

// frontend-react/src/app/modules/administraciones/articles/modals/ArticleCreate.js
import React, { Component } from 'react';
import { Navigate } from 'react-router-dom';
import Axios from 'axios';
import SimpleReactValidator from 'simple-react-validator';
import Swal from 'sweetalert';

import Global from './../../../../app-config/Default';
import Sidebar from './../../../../layout/sidebar/Sidebar';

class ArticleCreate extends Component {
  state = {
    article: {},
    status: null,
    selectedFile: null
  };
  url = Global.url;

  titleRef = React.createRef();
  contentsRef = React.createRef();

  constructor(props) {
    super(props);
    this.validator = new SimpleReactValidator();
  }

  changeState = () => {
    this.setState({
      article: {
        title: this.titleRef.current.value,
        content: this.contentsRef.current.value
      }
    });
  };

  fileChange = (event) => {
    this.setState({
      selectedFile: event.target.files[0]
    })
  };

  formSubmit = (e) => {
    e.preventDefault();
    if (this.validator.allValid()) {
      let urlArticle = this.url + '/article';
      Axios.post(urlArticle, this.state.article).then(response => {
        this.setState({
          article: response.data.articleStored,
          status: 'waiting'
        });
        if (this.state.selectedFile !== null) {
          let idArticle = response.data.articleStored._id;
          let formData = new FormData();
          let urlImageArticle = this.url + '/article/upload/' + idArticle;

          formData.append('file0', this.state.selectedFile, this.state.selectedFile.name);

          Axios.post(urlImageArticle, formData).then(responseFile => {
            this.setState({
              article: responseFile.data.article,
              status: responseFile.data.status
            });
          });
        } else {
          this.setState({
            status: response.data.status
          });
        }
        Swal({
          title: "Articulo creado!",
          text: "El articulo se ha creado correctamente!",
          icon: response.data.status
        });
      }).catch(function (error) {
        this.setState({
          status: error.data.status
        });
        Swal({
          title: "Error al crear!",
          text: error.data.message,
          icon: error.data.status
        });
      });
    } else {
      this.setState({
        status: 'faild'
      });
      this.validator.showMessages();
      this.forceUpdate();
    }
  };

  render() {
    if (this.state.status === 'success') {
      return <Navigate to={'/blog'} />
    }
    return (
      <React.Fragment>
        <div className="center">
          <section id="content">
            <h1 className="subheader">Crear artículo</h1>
            <form className="mid-form" onSubmit={this.formSubmit}>
              <div className="form-group">
                <label htmlFor="title">Titulo</label>
                <input type="text" name="title" id="title" ref={this.titleRef} onChange={this.changeState} required />
                {this.validator.message('title', this.state.article.title, 'required|min:5|max:50')}
              </div>

              <div className="form-group">
                <label htmlFor="contents">Contenido</label>
                <textarea name="contents" id="contents" ref={this.contentsRef} onChange={this.changeState} required></textarea>
                {this.validator.message('contents', this.state.article.content, 'required|min:10|max:150')}
              </div>

              <div className="form-group">
                <input type="file" name="file0" id="imagen" accept=".jpg, .jpeg, .png" aria-label="file0" onChange={this.fileChange} />
              </div>

              <div className="clearfix"></div>
              <input type="submit" value="Crear" className="btn btn-success" />
            </form>
          </section>
          <Sidebar />
        </div>
      </React.Fragment>
    );
  }
}

export default ArticleCreate;
