// frontend-vue/src/components/layout/header/HeaderComponent.vue
<template>
  <header id="header">
    <div class="center">
      <!-- LOGO -->
      <div id="logo">
        <img src="./../../../assets/images/vue.png" class="app-logo" alt="Logotipo" />
        <span id="brand">
          <strong>Curso</strong>Vue
        </span>
      </div>

      <!-- MENU -->
      <nav id="menu">
        <ul>
          <li>
            <RouterLink to="/inicio" active-class="active">Inicio</RouterLink>
          </li>
          <li>
            <RouterLink to="/blog" active-class="active">Blog</RouterLink>
          </li>
          <li>
            <RouterLink to="/formulario" active-class="active">Formulario</RouterLink>
          </li>
          <li>
            <RouterLink to="/peliculas" active-class="active">Peliculas</RouterLink>
          </li>
          <li>
            <RouterLink :to="{ path: 'pagina', name: 'PaginaComponent', params: { id: 'Soy el valor desde un parametro' } }" active-class="active">Pagina</RouterLink>
          </li>
        </ul>
      </nav>

      <!-- LIMMPIAR FLOTADO -->
      <div class="clearfix"></div>
    </div>
  </header>
</template>

<script>
export default {
  name: 'HeaderComponent'
}
</script>

// frontend-angular/src/app/layout/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {

  constructor(
    readonly translate: TranslateService
  ) { }

  ngOnInit(): void {

  }

  useLanguage(language: string) {
    this.translate.use(language);
  }
}

<header id="header">
    <div class="center">
        <!-- LOGO -->
        <div id="logo">
            <img src="./assets/images/angular.svg" class="app-logo" alt="Logotipo" />
            <span id="brand" [ngxSummernoteView]="'TextosAplicacion.TotalRegistrosPreTable' | translate"></span>
        </div>

        <div>
            <select id="langSelect" name="langSelect" aria-label="langSelect" #langSelect (change)="useLanguage(langSelect.value)">
                <option value="es">Español</option>
                <option value="en">Ingles</option>
            </select>
        </div>

        <!-- MENU -->
        <nav id="menu">
            <ul>
                <li>
                    <a [routerLink]="['/inicio']" [routerLinkActive]="['active']">{{ 'Menu.Inicio' | translate }}</a>
                </li>
                <li>
                    <a [routerLink]="['/blog']" [routerLinkActive]="['active']">{{ 'Menu.Blog' | translate }}</a>
                </li>
                <li>
                    <a [routerLink]="['/formulario']" [routerLinkActive]="['active']">{{ 'Menu.Formulario' | translate }}</a>
                </li>
                <li>
                    <a [routerLink]="['/peliculas']" [routerLinkActive]="['active']">{{ 'Menu.Peliculas' | translate }}</a>
                </li>
                <li>
                    <a [routerLink]="['/pagina']" [routerLinkActive]="['active']">{{ 'Menu.Pagina' | translate }}</a>
                </li>
            </ul>
        </nav>

        <!-- LIMMPIAR FLOTADO -->
        <div class="clearfix"></div>
    </div>        
</header>
