// frontend-vue/src/components/modules/administraciones/blog/BlogComponent.vue
<template>
  <div class="general">
    <SliderComponent :isViewButton="false" :defaultText="'Blog'" :size="'small'"></SliderComponent>
    <div class="center">
      <section id="content">
        <h2 class="subheader">Blog</h2>
      </section>
      <SidebarComponent></SidebarComponent>
      <div class="clearfix"></div>
    </div>
  </div>
</template>
<script>
import SliderComponent from './../../../layout/slider/SliderComponent.vue';
import SidebarComponent from './../../../layout/sidebar/SidebarComponent.vue';

export default {
  name: 'BlogComponent',
  components: {
    SliderComponent,
    SidebarComponent
  }
}
</script>

// frontend-react/src/app/modules/administraciones/blog/Blog.js
import React, { Component } from 'react';

import Sidebar from './../../../layout/sidebar/Sidebar';
import Slider from './../../../layout/slider/Slider';

class Blog extends Component {
  render() {
    return (
      <React.Fragment>
        <Slider nombre="Blog" />
        <div className="center">
          <section id="content">
            <h2 className="subheader">Blog</h2>
          </section>
          <Sidebar />
        </div>
      </React.Fragment>
    );
  }
}

export default Blog;
