// frontend-vue/src/components/modules/administraciones/articles/ArticlesComponent.vue
<template>
  <div id="articles" v-if="articles && articles.length > 0">
    <article class="article-item" v-for="article in articles" v-bind:key="article._id">
      <div class="image-wrap">
        <img v-if="article.image" :src="url + '/article/imagen/' + article.image" :alt="article.title" />
        <img v-if="!article.image" src="./../../../../assets/images/default.jpg" alt="Image Default" />
      </div>
      <h2>{{ article.title }}</h2>
      <span class="date">
        {{ article.date }}
      </span>
      <RouterLink to="/blog/articulo">Leer más</RouterLink>
      <div class="clearfix"></div>
    </article>
  </div>
</template>
<script>
import Global from './../../../app-config/Default';

export default {
  name: 'ArticlesComponent',
  props: {
    articles: {
      type: Object
    }
  },
  data() {
    return {
      url: Global.url
    };
  }
}
</script>

// frontend-react/src/app/modules/administraciones/articles/Articles.js
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import Axios from 'axios';
import Moment from 'react-moment';

import DefaultImage from './../../../../assets/images/default.jpg';
import Global from './../../../app-config/Default';

class Articles extends Component {
  state = {
    articles: [],
    status: null
  };
  url = Global.url;

  componentDidMount() {
    this.getArticles();
  }

  getArticles = () => {
    let lastArticles = this.props.lastArticles;
    let searchedArticle = this.props.searchedArticle;
    let urlArticles = this.url + '/articles';

    if (lastArticles && !searchedArticle) {
      urlArticles += '/' + lastArticles;
    } else if (!lastArticles && searchedArticle) {
      urlArticles = this.url + '/article/search/' + searchedArticle;
    }

    Axios.get(urlArticles).then(response => {
      this.setState({
        articles: response.data.articles,
        status: response.data.status
      });
    }).catch(function (error) {
      this.setState({
        articles: [],
        status: error.data.status
      });
    });
  }

  render() {
    if (this.state.articles.length > 0 && this.state.status === 'success') {
      let listArticles = this.state.articles.map((article) => {
        return (
          <article key={article._id} className="article-item" id={"article-template-" + article._id}>
            <div className="image-wrap">
              {
                article.image !== null ? (
                  <img src={this.url + '/article/imagen/' + article.image} alt={article.title} />
                ) : (
                  <img src={DefaultImage} alt={article.title} />
                )
              }
            </div>
            <h2>{article.title}</h2>
            <span className="date">
              <Moment locale='es' fromNow>{article.date}</Moment>
            </span>
            <Link to={'/blog/articulo/' + article._id}>Leer más</Link>
            <div className="clearfix"></div>
          </article>
        );
      });
      return (
        <section id="content">
          <div id="articles">
            {listArticles}
          </div>
        </section>
      );
    } else {
      return (
        <div id="articles" className="loading">
          <h2 className='subheader'>No hay articulos para mostrar</h2>
        </div>
      );
    }
  }
}

export default Articles;
