// frontend-vue/src/App.vue
<template>
  <div id="app">
    <HeaderComponent></HeaderComponent>
    <SliderComponent></SliderComponent>
    <div class="center">
      <RouterView></RouterView>
      <SidebarComponent></SidebarComponent>
      <div class="clearfix"></div>
    </div>
    <FooterComponent></FooterComponent>
  </div>
</template>

<script>
import HeaderComponent from './components/layout/header/HeaderComponent.vue';
import SliderComponent from './components/layout/slider/SliderComponent.vue';
import SidebarComponent from './components/layout/sidebar/SidebarComponent.vue';
import FooterComponent from './components/layout/footer/FooterComponent.vue';

export default {
  name: 'App',
  components: {
    HeaderComponent,
    SliderComponent,
    SidebarComponent,
    FooterComponent
  }
}
</script>

<style src="./assets/css/styles.css"></style>

// frontend-react/src/App.js
import './../src/assets/css/App.css';
import Header from './app/layout/header/Header';
import Slider from './app/layout/slider/Slider';
import Sidebar from './app/layout/sidebar/Sidebar';
import Footer from './app/layout/footer/Footer';
import Inicio from './app/modules/app/inicio/Inicio';

function App() {
  return (
    <div>
      <Header />
      <Slider />
      <div className="center">
        <Inicio />
        <Sidebar />
        <div className="clearfix"></div>
      </div>
      <Footer />
    </div>
  );
}

export default App;
