// frontend-react/src/app/modules/administraciones/peliculas/modals/Pelicula.js
import React, { Component } from 'react';
import { Link } from 'react-router-dom';

class Pelicula extends Component {
  seleccionarPelicula = () => {
    this.props.seleccionarPelicula(this.props.pelicula);
  };

  render() {
    const { title, year, image } = this.props.pelicula;
    return (
      <div id="articles">
        <article className="article-item" id={"article-template-" + this.props.index}>
          <div className="image-wrap">
            <img src={image} alt={title} />
          </div>
          <h2>{title}</h2>
          <span className="date">
            {year}
          </span>
          <Link to="/blog">Leer más</Link>
          <button onClick={this.seleccionarPelicula}>Seleccionar como favorita</button>
          <div className="clearfix"></div>
        </article>
      </div>
    );
  }
}

export default Pelicula

// frontend-vue/src/components/modules/administraciones/peliculas/models/PeliculaComponent.vue
<template>
  <article class="article-item">
    <div class="image-wrap">
      <img :src="movie.image" :alt="movie.title" :title="movie.title" />
    </div>
    <h2>{{ movie.title }}</h2>
    <span :class="{ 'year-green': movie.year > 2020, 'year-red': movie.year <= 2020 }">
      {{ movie.year }}
    </span>
    <RouterLink to="/blog">Leer más</RouterLink>
    <button @click=selectMovie(movie)>Seleccionar como favorita</button>
    <div class="clearfix"></div>
  </article>
</template>
<script>
export default {
  name: 'PeliculaComponent',
  props: {
    movie: {
      type: Object,
    }
  },
  methods: {
    selectMovie(movie) {
      this.$emit('showFavoriteMovie', movie);
    }
  }
}
</script>
