// frontend-angular/src/app/modules/administraciones/articles/articles.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Global } from 'src/app/app-config/default';
import { Article } from './services/article';

@Component({
  selector: 'app-articles',
  templateUrl: './articles.component.html',
  styleUrls: ['./articles.component.css']
})
export class ArticlesComponent implements OnInit {
  @Input() articles: Article[] = [];
  url!: string;
  
  constructor() { 
    this.url = Global.url;
  }

  ngOnInit(): void {
    
  }
}

<div class="loading" *ngIf="articles && articles.length <= 0">
    No hay articulos para mostrar
</div>
<div id="articles" *ngIf="articles && articles.length > 0">
    <article class="article-item" id="article-template-{{i}}" *ngFor="let
        article of articles; let i= index">
        <div class="image-wrap">
            <img src="{{ url + '/article/imagen/' + article.image }}" 
            alt="{{article.title }}" 
            onerror="this.onerror=null;this.src='assets/images/default.jpg'" />
        </div>
        <h2>{{ article.title }}</h2>
        <span class="date">
            {{ article.date | amLocale: 'es' | amTimeAgo }}
        </span>
        <a [routerLink]="['/blog/articulo', article._id]">Leer más</a>
        <div class="clearfix"></div>
    </article>
</div>

// frontend-vue/src/components/modules/administraciones/articles/ArticlesComponent.vue
<template>
  <div id="articles" v-if="articles && articles.length > 0">
    <article class="article-item" v-for="article in articles" v-bind:key="article._id">
      <div class="image-wrap">
        <img v-if="article.image" :src="url + '/article/imagen/' + article.image" :alt="article.title" />
        <img v-if="!article.image" src="./../../../../assets/images/default.jpg" alt="Image Default" />
      </div>
      <h2>{{ article.title }}</h2>
      <span class="date">
        {{ article.date }}
      </span>
      <RouterLink to="/blog/articulo">Leer más</RouterLink>
      <div class="clearfix"></div>
    </article>
  </div>
</template>
<script>
import Global from './../../../app-config/Default';

export default {
  name: 'ArticlesComponent',
  props: {
    articles: {
      type: Object
    }
  },
  data() {
    return {
      url: Global.url
    };
  }
}
</script>
